
services:
  # 1. Tu aplicación Django (UM)
  web:
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./chrome_data:/app/chrome_user_data
    ports:
      - "8017:8000"
    depends_on:
      - db
    networks:             # <--- NUEVO: Se une a la red compartida
      - red_global_proyectos

  # 2. El Servicio de PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_dsicom  # <--- NUEVO: Nombre fijo para que DatMail lo encuentre
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dsi_com_db
      - POSTGRES_USER=dsi_user
      - POSTGRES_PASSWORD=dsi1212A
      - OLLAMA_HOST=http://host.docker.internal:11434/api/generate
      - DJANGO_ALLOWED_HOSTS=*
    ports:
      - "5438:5432"
    networks:             # <--- NUEVO: Se une a la red compartida
      - red_global_proyectos
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:

# 3. Definición de la Red Compartida
networks:
  red_global_proyectos:
    name: red_global_proyectos  # Nombre explícito para usarlo en otros proyectos
    driver: bridge
